name: CI

on:
  push:
    paths:
      - "010/**"
      - "020/**"
      - "030/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npx eslint --cache .
