name: ESLint

on:
  push:
    paths:
      - '010/**'
      - '020/**'
      - '030/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: 🤔
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npx eslint --cache --fix .
      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9 # tag=v9
        if: always()
        with:
          message: 'chore(eslint): 🤖 ✨'
