name: ESLint

on:
  push:
    paths:
      - '010/**'
      - '020/**'
      - '030/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: 🤔
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cwd: ['010', '020', '030']
    defaults:
      run:
        working-directory: ${{ matrix.cwd }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: ${{ matrix.cwd }}/package-lock.json
      - run: npm ci
      - run: npx eslint --cache --quiet --fix .
      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9 # tag=v9
        if: always()
        with:
          message: 'chore(eslint): 🤖 ✨'
